name: Build on Tag

on:
  push:
    branches: 'TwistedScarlett'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update package repositories
      run: sudo apt-get update
      
    - name: Install latest GNU gold linker
      run: sudo apt-get install binutils-gold
      
    - name: Verify linker version
      run: ld.gold --version
      
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Dark-Ages-Último
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: b1c1_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
